name: Python AutoPEP8

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  autopep8-check:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11.7'

    - name: Install autopep8
      run: |
        python -m pip install --upgrade pip
        pip install autopep8

    - name: Run autopep8 on all Python files
      run: |
        find . -name "*.py" | xargs autopep8 --in-place --aggressive \
        --aggressive --max-line-length=79

    - name: Commit changes
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git add .
        git commit -m "Apply autopep8 formatting"

    - name: Push changes
      env:
        TOKEN: ${{ secrets.ACTIONS_PAT }}
      run: |
        git remote set-url origin https://x-access-token:${TOKEN}@github.com/${{ github.repository }}.git
        git push origin main
      continue-on-error: true
