name: Python AutoPEP8

on:
  push:
    branches: [ main ]

jobs:
  autopep8-check:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11.7'

    - name: Install autopep8
      run: |
        python -m pip install --upgrade pip
        pip install autopep8

    - name: Run autopep8 on modified Python files
      run: |
        git fetch --depth=2 # Fetch at least two commits for diff comparison
        DIFF_FILES=$(git diff --name-only --diff-filter=d HEAD~1 HEAD || \
        git diff --name-only --diff-filter=d $(git hash-object -t tree \
        /dev/null) HEAD)
        if [ -n "$DIFF_FILES" ]; then
          echo "$DIFF_FILES" | grep '\.py$' | xargs autopep8 --in-place \
          --aggressive --aggressive --max-line-length=79
        else
          echo "No Python files to format."
      
    - name: Commit changes
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git add .
        git commit -m "Apply autopep8 formatting"
        git push origin main
      continue-on-error: true
